# Generated by Django 4.1.1 on 2022-09-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='autor',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postagem',
            name='descricao',
            field=models.CharField(default=12, max_length=120),
            preserve_default=False,
        ),
    ]
